---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-tracker
  namespace: speedtest-tracker
spec:
  selector:
    matchLabels:
      app: speedtest-tracker
  template:
    metadata:
      labels:
        app: speedtest-tracker
    spec:
      containers:
      - name: speedtest-tracker
        image: lscr.io/linuxserver/speedtest-tracker:1.5.0
        envFrom:
          - secretRef:
              name: speedtest-tracker
        env:
          - name: DB_CONNECTION
            value: pgsql
          - name: DB_HOST
            value: 10.0.0.15
          - name: DB_PORT
            value: "5432"
          - name: DB_DATABASE
            value: speedtest_tracker
          - name: APP_URL
            value: https://speedtest.pycrs.cz
          - name: DISPLAY_TIMEZONE
            value: Europe/Prague
          - name: SPEEDTEST_SCHEDULE
            value: "*/15 * * * *"
        resources:
          limits:
            memory: 1Gi
            cpu: 1000m
          requests:
            memory: 512Mi
            cpu: 500m
        ports:
          - name: http
            containerPort: 80
          - name: https
            containerPort: 443

