version: '3'

services:
  bind9:
    container_name: bind9
    image: ubuntu/bind9:9.18-22.04_beta
    environment:
      - BIND9_USER=root
      - TZ=Europe/Prague
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./data/config:/etc/bind
      - ./data/cache:/var/cache/bind
      - ./data/records:/var/lib/bind
    networks:
      local_net:
        ipv4_address: 10.0.0.9
    restart: unless-stopped

networks:
  local_net:
    external: true