---
- name: "Unattended Pi-hole install"
  hosts: "{{ host }}"

  vars_files:
    - vars/secrets.yaml

  vars:
    config_path: "/etc/pihole/setupVars.conf"

  tasks:
    - name: Ensure directory exists.
      ansible.builtin.file:
        path: "{{ config_path | dirname }}"
        state: directory
    - name: Inject configuration.
      ansible.builtin.copy:
        dest: "{{ config_path }}"
        content: |
           QUERY_LOGGING=true
           INSTALL_WEB_SERVER=true
           WEBPASSWORD={{ web_password_hash }}
           INSTALL_WEB_INTERFACE=true
           LIGHTTPD_ENABLED=true
           WEBTHEME=default-dark
           PIHOLE_DNS_1={{ upstream01 }}
    - name: Install Pi-hole.
      ansible.builtin.shell:
        executable: "/bin/bash"
        cmd: |
          "curl -sSL https://install.pi-hole.net | bash /dev/stdin --unattended"