---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pycrs-cz
  namespace: traefik
spec:
  secretName: pycrs-cz-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.pycrs.cz"
  dnsNames:
    - "pycrs.cz"
    - "*.pycrs.cz"
