version: '3'

services:
  traefik:
    container_name: traefik
    restart: unless-stopped
    image: traefik:v3.0
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CF_API_EMAIL=${CLOUDFLARE_EMAIL}
      - CF_DNS_API_TOKEN=${CLOUDFLARE_DNS_TOKEN}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yaml:/traefik.yaml:ro
      - ./config/acme:/etc/traefik/acme
      - ./config/conf:/etc/traefik/conf
    networks:
      local_net:
        ipv4_address: 10.0.0.25
      proxy_net:
        ipv4_address: 172.21.0.254

networks:
  local_net:
    external: true
  proxy_net:
    external: true