api:
  dashboard: true

log:
  level: DEBUG

entryPoints:
  http:
    address: :80
  https:
    address: :443
    http:
      tls:
        certResolver: letsencrypt
        domains:
          - main: "pycrs.cz"
            sans:
              - "*.pycrs.cz"
          - main: "remeslovkostce.cz"
            sans:
              - "*.remeslovkostce.cz"

serversTransport:
  # Allow self signed certs
  insecureSkipVerify: true

certificatesResolvers:
  letsencrypt:
    acme:
      # Don't need renewal notifications
      email:
      storage: /etc/traefik/acme/letsencrypt.json
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: /etc/traefik/conf
    watch: true