apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: traefik

spec:
  certificates:
    - secretName: gitlab-pycrs-cz-production-tls
  defaultCertificate:
    secretName: pycrs-cz-production-tls