---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
spec:
  schedule: '@hourly'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 100
      template:
        spec:
          containers:
            - name: homelab
              image: renovate/renovate:41.17.2
              env:
                - name: RENOVATE_AUTODISCOVER
                  value: "true"
                - name: RENOVATE_PLATFORM
                  value: gitlab
              envFrom:
                - secretRef:
                    name: renovate
#            - name: skoda-auto
#              image: renovate/renovate:41.17.2
#              args:
#                - "pycrs-epa/graph-insights"
#              env:
#                - name: RENOVATE_PLATFORM
#                  value: gitlab
#              envFrom:
#                - secretRef:
#                    name: renovate-gitlab-com
          restartPolicy: Never