---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
spec:
  schedule: '@hourly'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renovate
              image: renovate/renovate:41.17.2
              env:
                - name: RENOVATE_AUTODISCOVER
                  value: "true"
                - name: RENOVATE_PLATFORM
                  value: gitlab
              envFrom:
                - secretRef:
                    name: renovate
          restartPolicy: Never