---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: homepage
    namespace: homepage 
    labels:
        app.kubernetes.io/name: homepage
spec:
    replicas: 1
    strategy:
        type: RollingUpdate
    selector:
        matchLabels:
            app.kubernetes.io/name: homepage
    template:
        metadata:
            labels:
                app.kubernetes.io/name: homepage
        spec:
            serviceAccountName: homepage
            automountServiceAccountToken: true
            dnsPolicy: ClusterFirst
            containers:
                - name: homepage
                  image: "ghcr.io/gethomepage/homepage:latest"
                  imagePullPolicy: Always
                  ports:
                      - name: http
                        containerPort: 3000
                        protocol: TCP
                  env:
                    - name: HOMEPAGE_VAR_JELLYFIN_API_KEY
                      valueFrom:
                        secretKeyRef:
                          key: api-key
                          name: jellyfin
                    - name: HOMEPAGE_VAR_JELLYSEER_API_KEY 
                      valueFrom:
                        secretKeyRef:
                          key: api-key
                          name: jellyseer
                  volumeMounts:
                      - name: homepage-config
                        mountPath: /app/config
                      - name: logs
                        mountPath: /app/config/logs
            volumes:
                - name: homepage-config
                  configMap:
                      name: homepage
                - name: logs
                  emptyDir: {}