---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-deployment
  namespace: traefik
  labels:
    app: traefik

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-account
      containers:
        - name: traefik
          image: traefik:v3.1.4
          args:
            - --providers.kubernetesingress
            - --providers.kubernetescrd
            - --providers.file.directory=/etc/traefik/conf
            - --providers.file.watch=true
            - --serversTransport.insecureSkipVerify=true
            - --api.dashboard=true
            - --entryPoints.http.address=:80
            - --entryPoints.https.address=:443
            - --entryPoints.smtps.address=:465
            - --log.level=DEBUG
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
            - name: smtps
              containerPort: 465 
          volumeMounts:
            - name: dynamic-configuration
              mountPath: /etc/traefik/conf
      volumes:
        - name: dynamic-configuration
          configMap:
            name: dynamic-configuration
