---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dashboard
  namespace: traefik
spec:
  entryPoints: [https]
  routes:
  - kind: Rule
    match: Host(`kube.traefik.pycrs.cz`)
    services:
    - kind: TraefikService
      name: api@internal
  tls:
    domains:
    - main: kube.traefik.pycrs.cz