---
apiVersion: v1
kind: Service
metadata:
  name: traefik-service
  namespace: traefik

spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: 10.0.0.214
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
    - name: smtps 
      port: 465
  selector:
    app: traefik