# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/bookmarks

- Developer:
    - Github:
        - href: https://github.com/Pzdrs
          icon: github-light.png
- Social:
    - Reddit:
        - href: https://reddit.com/
          icon: reddit.png
    - Instagram:
        - href: https://www.instagram.com/
          icon: instagram.png
    - Facebook:
        - href: https://www.facebook.com/
          icon: facebook.png

- Entertainment:
    - YouTube:
        - icon: youtube-play.png
          href: https://youtube.com/
    - Netflix:
        - href: https://netflix.com/
          abbr: NE
    - Disney+:
        - href: https://www.disneyplus.com/home
          abbr: D+