---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/services

- Network infrastructure & monitoring:
    - pfSense:
        icon: pfsense.png
        href: https://10.0.0.1:10443
    - Speedtest Tracker:
        icon: speedtest-tracker.png
        href: https://speedtest.pycrs.cz
        widget:
            type: speedtest
            url: http://10.0.0.15:8765
    - UniFi Controller:
        icon: unifi.png
        href: https://unifi.pycrs.cz
    - Pi-hole (primary):
        icon: pi-hole.png
        href: https://pihole1.pycrs.cz
        ping: http://10.0.0.2
        widget:
            type: pihole
            url: http://10.0.0.2
    - Pi-hole (secondary):
        icon: pi-hole.png
        href: https://pihole1.pycrs.cz
        ping: http://10.0.0.3
        widget:
            type: pihole
            url: http://10.0.0.3
    - Traefik:
        icon: traefik.png
        href: https://traefik.pycrs.cz
    - Uptime-kuma:
        icon: uptime-kuma.png
        href: https://uptime-kuma.pycrs.cz
    - Guacamole:
        icon: guacamole.png
        href: https://guacamole.pycrs.cz
- Media management:
    - Jellyfin:
        icon: jellyfin.png
        href: https://jellyfin.pycrs.cz
        widget:
            type: jellyfin
            url: http://10.0.0.10:9001
            key: {{HOMEPAGE_VAR_JELLYFIN_API_KEY}}
    - Jellyseer:
        icon: jellyseerr.png
        href: https://jellyseer.pycrs.cz
        widget:
            type: jellyseerr
            url: http://10.0.0.10:10241
            key: {{HOMEPAGE_VAR_JELLYSEER_API_KEY}}
    - Radarr:
        icon: radarr.png
        href: https://radarr.pycrs.cz
        widget:
            type: radarr
            url: http://10.0.0.10:7878
            key: {{HOMEPAGE_VAR_RADARR_API_KEY}}
    - Sonarr:
        icon: sonarr.png
        href: https://sonarr.pycrs.cz
        widget:
            type: sonarr
            url: http://10.0.0.10:8989
            key: {{HOMEPAGE_VAR_SONARR_API_KEY}}
    - Prowlarr:
        icon: prowlarr.png
        href: https://prowlarr.pycrs.cz
        widget:
            type: prowlarr
            url: http://10.0.0.10:9696
            key: {{HOMEPAGE_VAR_PROWLARR_API_KEY}}
    - qBittorrent:
        icon: qbittorrent.png
        href: https://qbittorrent.pycrs.cz
        widget:
            type: qbittorrent
            url: http://10.0.0.10:10095
            username: {{HOMEPAGE_VAR_QBITTORRENT_USERNAME}}
            password: {{HOMEPAGE_VAR_QBITTORRENT_PASSWORD}}
- Data analysis:
    - Grafana:
        icon: grafana.png
        href: https://grafana.pycrs.cz
        server: my-remote-docker
        container: grafana
    - InfluxDB:
        icon: influxdb.png
        href: https://influx.pycrs.cz
        server: my-remote-docker
        container: influxdb2
    - Node-RED:
       icon: node-red.png
       href: https://node-red.pycrs.cz
       server: my-remote-docker
       container: node-red
- Miscellaneous:
    - Portainer:
        icon: portainer.png
        href: https://portainer.pycrs.cz
        server: my-remote-docker
        container: portainer
        widget:
            type: portainer
            url: https://10.0.0.15:9443
            env: 2
            key: {{HOMEPAGE_VAR_PORTAINER_API_KEY}}
    - Proxmox:
        icon: proxmox.png
        href: https://pve1.pycrs.cz
        widget:
            type: proxmox
            url: https://10.0.0.254:8006
            username: {{HOMEPAGE_VAR_PVE1_USERNAME}}
            password: {{HOMEPAGE_VAR_PVE1_PASSWORD}}
    - Proxmox Backup Server:
        icon: proxmox.png
        href: https://pbs1.pycrs.cz
        #widget:
            #type: proxmoxbackupserver
            #url: https://10.0.0.30:8007
            #username: {{HOMEPAGE_VAR_PBS1_USERNAME}}
            #password: {{HOMEPAGE_VAR_PBS1_PASSWORD}}
    - TrueNAS SCALE:
        icon: truenas.png
        href: https://scale.pycrs.cz
        widget:
            type: truenas
            url: https://10.0.0.10
            key: {{HOMEPAGE_VAR_TRUENAS_API_KEY}}
    - HomeAssistant:
        icon: home-assistant.png
        href: https://hass.pycrs.cz